### PR TITLE
Make page headers fixed

### LINKED ISSUE #369: Header doesn't stay in place when scrolling
See example:

screencast 2018-07-09 17-55-08

### PR DESCRIPTION
**Pull request by LordZardeck**
Fixes #369

### CODE REVIEW

**Comment by LordZardeck** [comment]
screencast 2018-07-12 09-49-35
screencast 2018-07-12 09-59-42

**Comment by toddmedema** [comment]
@LordZardeck just deployed the fix for loot points - just need to log into your account once via the App or Quest Creator and I'll get those points added :) Thanks again!

**Comment by LordZardeck** [comment]
@toddmedema Logged in, anything else i need to do?

**Comment by toddmedema** [comment]
Nope, all set and points awarded!

**Comment by LordZardeck** [comment]
@toddmedema Is there any where I can see these points? I don't see them in the quest creator

**Comment by toddmedema** [comment]
Should be in the top right corner of the Quest Creator, next to your email. Just awarded 300 points to your s***@t******.io email

**Comment by toddmedema** [comment]
...yep, that's where it's supposed to show up! 

Ah, might be an old version of the quest creator (haven't been able to deploy the UI in a few weeks since there's a pretty big bug in it) - I bet if you go to the /auth network request, you'll see the appropriate amount of loot points in the response

**Pull request merged**
