### PR TITLE
Add support for iPhone X

### PR DESCRIPTION
**Pull request by LordZardeck**
Closes https://github.com/ExpeditionRPG/expedition/issues/366

### CODE REVIEW

**Comment by LordZardeck** [comment]
@toddmedema You should have permission now

**Comment by LordZardeck** [comment]
@toddmedema can you show me what you are seeing. This is on my screen:

expedition rpg companion app 2018-07-09 22-51-29

**Comment by toddmedema** [comment]
Homepage actually looks fine on my computer too, but it's the next page that's off when simulating both the iPhone X and other mobile device screens - 

screen shot 2018-07-09 at 23 54 51
screen shot 2018-07-09 at 23 55 01

**Comment by LordZardeck** [comment]
@toddmedema Good catch on that. I left a debugging style in there. It's removed now

**Comment by LordZardeck** [comment]
@toddmedema when do you think this will be released?

**Comment by toddmedema** [comment]
Approved and merged! Congratulations on your first PR :)

Interested in tackling another? Given your CSS skills, I bet you could solve https://github.com/ExpeditionRPG/expedition/issues/369 in no time

**Comment by toddmedema** [comment]
Hoping to get a few more bugfixes in, so tentatively Friday or Saturday

**Comment by LordZardeck** [comment]
Cool. How does the loot thing work?

**Comment by toddmedema** [comment]
Email me at todd@fabricate.io with your Expedition account email and I'll credit your account with points for each merged PR :)

**Pull request merged**
