### PR TITLE
This does it.

### PR DESCRIPTION
**Pull request by ezittel**
If I just copy the dispatch here as well this seems to work.

### CODE REVIEW

**Comment by ezittel** [comment]
what I want to do is to use the if to determine if we need to search privately, then wrap this bit:


```
dispatch(getSearchResults(params, (quests: QuestDetails[], response: any) => {
    dispatch({
      type: 'SEARCH_RESPONSE',
      quests: quests,
      nextToken: response.nextToken,
      receivedAt: response.receivedAt,
      search: params,
    } as SearchResponseAction);

  }));
```
with this with appropriate phase type
dispatch(toCard({name: 'SEARCH_CARD', phase: 'PRIVATE'}));

So far I've just got syntax errors.

**Comment by toddmedema** [comment]
In that case, you would do `phase: 'PRIVATE' as CardName`, and you'd need to import CardName from wherever it's defined - but, I'd also be totally fine with us just moving the existing logic with those values hard-coded, ie `dispatch(toCard({name: 'SEARCH_CARD', phase: 'SEARCH'}));` - `resulty` only needs the additional typecast because it's being defined outside of the toCard call - if it's defined inside of it, Typescript knows to look for / expect an object of type `ToCardArgs`

**Comment by ezittel** [comment]
I tried moving the whole conditional if-block but found can't put it after that comma.  I haven't tried ternary yet, maybe that would work.

**Comment by toddmedema** [comment]
What's the code you're trying and what's the error?

**Comment by ezittel** [comment]
Okay this has been a good one to learn on.  I'm starting to understand the components and how they integrate a bit more.
I moved in CardPhase, but didn't need CardName.  This is working now and relatively clean as well!
Take a look.

**Comment by toddmedema** [comment]
@ezittel cool if we give you a shout-out in our upcoming fan newsletter to thank you for your contributions?

**Comment by ezittel** [comment]
Sure you can use my github name or Eric Zittel.

**Comment by toddmedema** [comment]
Hey Eric! Interested in tackling another issue? This one has your name on it :) https://github.com/ExpeditionRPG/expedition/issues/254

**Comment by ezittel** [comment]
Sorry, I meant to tell you sooner - I'm in the middle of selling one house, building and buying another, packing, and getting ready for the move in a few weeks.  I'm going to have to put Expedition coding aside for a little bit to focus on the domestic things of life.

I'll ping you when I get to a place where I can get back to this - I would expect end of summer or so.

Thanks!

**Comment by toddmedema** [comment]
That's exciting! Good luck with the move :)

**Comment by toddmedema** [comment]
Hope the move is going well! :)

**Comment by ezittel** [comment]
Yep - I've closed!
I'm just about to do the final furniture move and should be able to get back to ExpeditionRPG by October.
Thanks for thinking of me :)

**Comment by toddmedema** [comment]
Woohoo! That must be exciting :)

**Pull request merged**
