### PR TITLE
fix: styling of expansion checkboxes

### LINKED ISSUE #554: Incorrect styling of search page checkboxes
image

The expansion checkboxes select in bright pink, which doesn't match the style of the rest of the app. I expect this is because we're using regular MUI checkboxes here and not components/base/Checkbox.tsx.

### PR DESCRIPTION
**Pull request by nimish-gupta**
Fixes #554

### CODE REVIEW

**Comment by nimish-gupta** [comment]
https://www.useloom.com/share/ddf5dfe4fde041a7adccf253793d86de

**Comment by toddmedema** [comment]
Hmmm. Those look way too large / very out of place on the filters page, compared to the rest of the filters. Could you create a new CSS class on top of them that styles them closer to Selects?

(and then include screenshots of them on both mobile and desktop)

**Comment by nimish-gupta** [comment]
Web 
https://www.dropbox.com/s/frjpumrzlxgmwpi/Screenshot%202018-11-29%2023.36.30.png?dl=0
Mobile
https://www.dropbox.com/s/yknbyvy4tz9eol7/Screenshot%202018-11-29%2023.37.23.png?dl=0

**Comment by toddmedema** [comment]
Oooooh, shoot. Guess I did a bad job of explaining it. Didn't mean to actually make it a select - meant to keep them as checkboxes, but change their font size / padding / etc to fit in better visually fit in with the rest of the page. Sorry about that! (let me know if that's still not clear and I can do a quick photoshop of what I mean)

**Comment by nimish-gupta** [comment]
Ohhh, sorry my bad, got it, i will change it back to checkboxes. And make
them similar to the current form ui.

**Comment by nimish-gupta** [comment]
Web https://www.dropbox.com/s/et7czzpqj7odnca/Screenshot%202018-11-30%2023.03.07.png?dl=0
Mobile https://www.dropbox.com/s/6632igugac4evt8/Screenshot%202018-11-30%2023.04.41.png?dl=0
If still change can you please attach the photoshop?

**Pull request merged**
